name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build with Maven
      run: mvn clean install

    - name: Run SonarQube Analysis
      run: mvn sonar:sonar -Dsonar.host.url=http://172.17.0.2:9000 -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }} -Dsonar.projectKey=demoSonar
